Revert "media/gpu/v4l2: setup V4L2 AV1 decoding loop filter params"
This reverts commit 608ec0dede18ffba1b6bc63f34baf0b8606ddf79.

Reason for revert: Causing build failure on https://ci.chromium.org/p/chrome/builders/ci/chromeos-kevin-chrome

eg. in https://ci.chromium.org/ui/p/chrome/builders/ci/chromeos-kevin-chrome/22811/overview
[3446/6985] CXX obj/media/gpu/v4l2/v4l2_stateless_decoder/av1_decoder.o
FAILED: obj/media/gpu/v4l2/v4l2_stateless_decoder/av1_decoder.o
../../build/cros_cache/chrome-sdk/symlinks/kevin+14844.0.0+target_toolchain/bin/armv7a-cros-linux-gn...(too long)
In file included from ../../media/gpu/v4l2/test/av1_decoder.cc:5:
In file included from ../../media/gpu/v4l2/test/av1_decoder.h:13:
../../build/cros_cache/chrome-sdk/symlinks/kevin+14844.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz/usr/include/linux/media/av1-ctrls.h:249:2: error: unknown type name 'u8'
u8 flags;
^
1 error generated.
[3467/6985] CXX obj/media/gpu/v4l2/v4l2_stateless_decoder/v4l2_stateless_decoder.o

Original change's description:
> media/gpu/v4l2: setup V4L2 AV1 decoding loop filter params
>
> This CL prepares the following loop filter parameters for AV1 decoding
> using V4L2 API.
> - Section 5.9.11. Loop filter params syntax in AV1 spec.
> - Section 5.9.18. Loop filter delta parameters syntax.
>   https://aomediacodec.github.io/av1-spec/av1-spec.pdf
>
> These parameters are needed to make VIDIOC_S_EXT_CTRLS V4L2 ioctl call.
>
> Bug: b:228534730
> TEST: v4l2_stateless_decoder --video=00000527_20210205.ivf --frames=1 --v=4 on cherry/tomato using mainline
> Change-Id: I158ecaf45c02c8eb9275239a8e9c7871539c2db3
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3652013
> Reviewed-by: Fritz Koenig <frkoenig@chromium.org>
> Commit-Queue: Steve Cho <stevecho@chromium.org>
> Reviewed-by: Miguel Casas-Sanchez <mcasas@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1008008}

Bug: b:228534730
Change-Id: I6afe179a5d015967f44ea962bd2032509e00b71b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3670419
Auto-Submit: Glen Robertson <glenrob@chromium.org>
Owners-Override: Glen Robertson <glenrob@google.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1008129}
NOKEYCHECK=True
GitOrigin-RevId: 0e8707a054167bc7aedd3e9935238ada37161fea