media/gpu/chromeos: Fix chormium-style error in PlatformVideoFrameUtilsUnittest
The following chromium-style error is caused in building
media_unittests with target_os="chromeos" and use_vaapi=true.

"""
../../media/gpu/chromeos/platform_video_frame_utils_unittest.cc:73:33: error: [chromium-style] Overriding method must be marked with 'override' or 'final'.
  ~FakeGpuMemoryBufferFactory() {
                                ^
                                 override
"""

Bug: None
Test: Build media_unittests
Change-Id: Ib01d4aae4bf48629f0cdfd1295a2278ea198275b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2141753
Auto-Submit: Hirokazu Honda <hiroh@chromium.org>
Commit-Queue: Chih-Yu Huang <akahuang@chromium.org>
Reviewed-by: Chih-Yu Huang <akahuang@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#757689}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: f10378385bafffb36f9ab991448f8c4c6217a16e