Add missing buildflags dependency
This simple sequence fails to build:

    $ gn clean .
    $ ninja obj/media/gpu/vaapi/libva_stubs/va_stubs.o

The error is:

    gen/media/gpu/vaapi/va_stubs.cc:15:10: fatal error: 'media/gpu/buildflags.h' file not found

This is because of a missing dependency - Chromium has many.

Bug: 931596
Change-Id: Ied0fc8eb81ba4b119ee0442293634dd28112467c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3540992
Reviewed-by: Andres Calderon Jaramillo <andrescj@chromium.org>
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#983568}
NOKEYCHECK=True
GitOrigin-RevId: 8ea85ec4ad5b8d90efc5a85baf1fdebf3e97b2a4