Reland "Send right system capture muted status"
This is a reland of commit 8b2d3aa31ba24a6ce76df097ce56f6509994c9a8

If you encounter this error

FAILED: obj/media/audio/audio/cras_input.o
../../media/audio/cras/cras_input.cc:445:3: error: use of undeclared identifier 'libcras_client_get_system_capture_muted';

please check if your chromeos version is > 14934.0.0, if you trying to use chromeos sdk, please update your sdk and reopen it.

Original change's description:
> Send right system capture muted status
>
> Implement CrasInputStream::IsMuted to get real system capture muted
> status on chrome os.
>
> Bug: b/235164478
> Test: Open Google meet and muted system capture. See if there is a hint tell you your mic is muted by system.
>
> Change-Id: I7b3c32fea7c8441380b1e50853aeee2291682476
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3709279
> Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
> Commit-Queue: Ching Yun Chang <whalechang@google.com>
> Reviewed-by: Yu-Hsuan Hsu <yuhsuan@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1020729}

Bug: b/235164478
Change-Id: I3fbb432ef8a0da56e04a966c26272e6e745ef2bf
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3750663
Reviewed-by: Yu-Hsuan Hsu <yuhsuan@chromium.org>
Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
Commit-Queue: Ching Yun Chang <whalechang@google.com>
Reviewed-by: Leonid Baraz <lbaraz@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1022577}
NOKEYCHECK=True
GitOrigin-RevId: 6bbd003a76a612232cb830ecbb6e7105fabd5680