Revert "lacros: replicate USE_LIBV4L2 ash buildflag in lacros"
This reverts commit d779e562ed66c33d21694e9ef1adb19d52484f19.

Reason for revert: compilation failure seen in https://ci.chromium.org/ui/p/chromium/builders/ci/chromeos-kevin-rel/44412/overview :

media/gpu/v4l2/v4l2_device.cc:144:10: error: 'return' will never be executed [-Werror,-Wunreachable-code-return]
return false;

Original change's description:
> lacros: replicate USE_LIBV4L2 ash buildflag in lacros
>
> The USE_LIBV4L2 buildflag is not available in lacros. In lacros, this CL
> checks if the library file is in the file system to replicate the
> USE_LIBV4L2 buildflag behaviour in ash. This works because the library
> will get installed only if the USE_LIBV4L2 buildflag is present in ash.
>
> BUG=b:240881905
> TEST=manual test on trogdor and kevin
>
> Change-Id: Id322e386a462cf18802e112635108a902f3fd27c
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3814276
> Reviewed-by: Zhenyao Mo <zmo@chromium.org>
> Reviewed-by: Jorge Lucangeli Obes <jorgelo@chromium.org>
> Reviewed-by: Hirokazu Honda <hiroh@chromium.org>
> Reviewed-by: Andres Calderon Jaramillo <andrescj@chromium.org>
> Commit-Queue: Pilar Molina Lopez <pmolinalopez@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1040020}

Bug: b:240881905
Change-Id: I390c02cefeb64dc4a081810efbd272614e696ce3
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3860155
Commit-Queue: David Baron <dbaron@chromium.org>
Auto-Submit: David Baron <dbaron@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Shu Yang <shuyng@google.com>
Cr-Commit-Position: refs/heads/main@{#1040039}
NOKEYCHECK=True
GitOrigin-RevId: d53c3855fe4400db953f2a0e2fba32e4113514de