Revert "AudioBus: Convert deprecated uses of FromInterleaved(Partial)/ToInterleaved, remove deprecated ToInterleavedPartial"
This reverts commit e8e3eced76a576b955f155e1a582011c03627d4d.

Reason for revert: Breaks Google ChromeOS compile

https://logs.chromium.org/logs/chromium/bb/chromium.chrome/Google_Chrome_ChromeOS/61651/+/recipes/steps/compile/0/logs/raw_io.output_failure_summary_/0

../../chromeos/services/assistant/audio_decoder/assistant_audio_decoder.cc:139:30: error: unknown type name 'SignedInt16SampleTypeTraits'; did you mean 'media::SignedInt16SampleTypeTraits'?
audio_bus->ToInterleaved<SignedInt16SampleTypeTraits>(audio_bus->frames(),
^~~~~~~~~~~~~~~~~~~~~~~~~~~
media::SignedInt16SampleTypeTraits
../../media/base/audio_sample_types.h:213:7: note: 'media::SignedInt16SampleTypeTraits' declared here
using SignedInt16SampleTypeTraits = FixedSampleTypeTraits<int16_t>;
^
../../chromeos/services/assistant/audio_decoder/assistant_audio_decoder.cc:139:16: error: no matching member function for call to 'ToInterleaved'
audio_bus->ToInterleaved<SignedInt16SampleTypeTraits>(audio_bus->frames(),
~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../media/base/audio_bus.h:265:16: note: candidate function template not viable: no known conversion from 'std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >::value_type *' (aka 'unsigned char *') to 'typename FixedSampleTypeTraits<short>::ValueType *' (aka 'short *') for 2nd argument
void AudioBus::ToInterleaved(
^
2 errors generated.

Original change's description:
> AudioBus: Convert deprecated uses of FromInterleaved(Partial)/ToInterleaved, remove deprecated ToInterleavedPartial
> 
> There is no intended behaviour change.
> 
> Bug: 619623
> Change-Id: I38a3b3b11d81fcec1278855592cde0c355c6e69a
> Reviewed-on: https://chromium-review.googlesource.com/c/1461388
> Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
> Reviewed-by: Sergey Ulanov <sergeyu@chromium.org>
> Reviewed-by: Yuri Wiitala <miu@chromium.org>
> Reviewed-by: Bill Budge <bbudge@chromium.org>
> Reviewed-by: Kenneth MacKay <kmackay@chromium.org>
> Reviewed-by: Tao Wu <wutao@chromium.org>
> Reviewed-by: Max Morin <maxmorin@chromium.org>
> Commit-Queue: Raul Tambre <raul@tambre.ee>
> Cr-Commit-Position: refs/heads/master@{#631900}

TBR=bbudge@chromium.org,dalecurtis@chromium.org,miu@chromium.org,sergeyu@chromium.org,maxmorin@chromium.org,kmackay@chromium.org,wutao@chromium.org,raul@tambre.ee

Change-Id: I4a9a09e8e1e8e5a316144a636dff204b9db74888
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 619623
Reviewed-on: https://chromium-review.googlesource.com/c/1471304
Reviewed-by: Devlin <rdevlin.cronin@chromium.org>
Commit-Queue: Devlin <rdevlin.cronin@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#631930}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 5b3ccb8677f7ac2c791f3e4b5f554dd5a50f3763