GCC: DecodeTimestamp::InMilliseconds cannot be constexpr.
Fix bug error in GCC because of using a non-constexpr inside a
constexpr. As making TimeDelta::InMilliseconds makes the binary
significantly bigger, this just removes constexpr for
DecodeTimestamp::InMilliseconds.

../../media/base/stream_parser_buffer.h:96:71: error: call to non-‘constexpr’ function ‘int64_t base::TimeDelta::InMilliseconds() const’
   96 |   constexpr int64_t InMilliseconds() const { return ts_.InMilliseconds(); }
      |                                                     ~~~~~~~~~~~~~~~~~~^~

Bug: 819294
Change-Id: I6d0fb6de7d42c857863827a568059f860505944f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3453082
Reviewed-by: Ted (Chromium) Meyer <tmathmeyer@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#971898}
NOKEYCHECK=True
GitOrigin-RevId: d7068c6878b52c382b40e543e1b7be5afae45c96